title: Batch Command Reference
description: A comprehensive guide to Windows batch commands
remote_theme: b2a3e8/jekyll-theme-console

#theme: jekyll-theme-hacker
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
