title: Batch Command Reference
description: A comprehensive guide to Windows batch commands
remote_theme: tomjoht/documentation-theme-jekyll
plugins:
  - jekyll-remote-theme

#theme: jekyll-theme-hacker
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
